### ISSUE TITLE
What's about upheaval - I mean <br /> or \n in messages

### ISSUE THREAD

**Issue by mitchobrian** [Detaysoft/react-chat-elements#120]
Do you have plans to support \n for upheaval?

**Comment by brendoncarvalho** [comment]
🙏

**Comment by mitchobrian** [comment]
My suggestion for this one:
https://github.com/Detaysoft/react-chat-elements/pull/122

**Comment by abdurrahmanekr** [comment]
It is enough to give the following to the **rce-mbox-text** class.

```css
.rce-mbox-text {
    white-space: pre-line;
}
```
