### ISSUE TITLE
How to set the background-color of chatItem ?

### ISSUE THREAD

**Issue by wayne4o312** [Detaysoft/react-chat-elements#199]
When I toggle the app theme mode, I want to toggle the background color of the component

**Comment by emregudur** [comment]
You can use rce-citem class for it.

```css
.rce-citem {
    background-color: red;
}
```
